### PR TITLE
RET-3602 - Add case linking to data model

### PR DESCRIPTION
**Pull request by marcjudge**
https://tools.hmcts.net/confluence/display/RCCD/CCD+Supported+Field+Types#CCDSupportedFieldTypes-ccdTypeCaseLink

<html>
<body>
<p style="margin: 0px; padding: 0px; color: rgb(23, 43, 77); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(250, 250, 210); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span style="color: rgb(36, 41, 46);">A </span><code style="font-family: SFMono-Medium, &quot;SF Mono&quot;, &quot;Segoe UI Mono&quot;, &quot;Roboto Mono&quot;, &quot;Ubuntu Mono&quot;, Menlo, Courier, monospace;">CaseLink</code><span style="color: rgb(36, 41, 46);"><span> </span>is a field used to reference another CCD case (which must exist) using its universal 16-digit ID.</span></p><p style="margin: 10px 0px 0px; padding: 0px; color: rgb(23, 43, 77); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(250, 250, 210); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span style="color: rgb(36, 41, 46);">It's a complex type composed of following sub-fields - </span></p><div class="table-wrap" style="margin: 10px 0px 0px; padding: 0px; overflow-x: auto; color: rgb(23, 43, 77); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(250, 250, 210); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Name | Type | Mandatory | Notes
-- | -- | -- | --
CaseReference | Text | Yes | Case reference number of the case being linked
ReasonForLink | Array | No | Array of the LinkReason base type
CreatedDateTime | DateTime | No | Date and time when the link was created
CaseType | Text | No | CCD case type id of the case being linked.

</div>
</body>
</html>

_LinkReason_
<html>
<body>
<p style="margin: 0px; padding: 0px; color: rgb(23, 43, 77); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span style="color: rgb(23, 43, 77);">This new standard base type is established to record a single reason for the case linking</span><span style="color: rgb(23, 43, 77);">.  It will contain the following fields:</span></p><div class="table-wrap" style="margin: 10px 0px 0px; padding: 0px; overflow-x: auto; color: rgb(23, 43, 77); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

FieldId | Type | Comments
-- | -- | --
Reason | Text | The reason selected to link to the target case
OtherDescription | Text | If other is selected then the user should add the reason to be stored in this attribute

</div><p style="margin: 10px 0px 0px; padding: 0px; color: rgb(23, 43, 77); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">The values stored will have been sourced from Reference Data (by ExUI).  It also supports 'Other' as a reason and in that case the OtherDescription field will store the free text description.</p>
</body>
</html>

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RET-3602

### Change description ###
Adding case linking functionality

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by GauravChawlaMOJ — APPROVED** [review]

**Review by GauravChawlaMOJ — COMMENTED** [review]
Looking at ticket again, may be create an enum for reasons (as we have pre-defined reasons?) rather than string?

**Comment by marcjudge** [comment]
> Looking at ticket again, may be create an enum for reasons (as we have pre-defined reasons?) rather than string?

@GauravChawlaMOJ I think this would defeat the purpose of using ref data, would it? We pull in whatever they have defined. If they want to add/remove reasons then we don't need to modify our code base.

**Comment by GauravChawlaMOJ** [comment]
> > Looking at ticket again, may be create an enum for reasons (as we have pre-defined reasons?) rather than string?
> 
> @GauravChawlaMOJ I think this would defeat the purpose of using ref data, would it? We pull in whatever they have defined. If they want to add/remove reasons then we don't need to modify our code base.

Why would it defeat the purpose? Every service has pre-defined link reasons. If they change it (unlikely though and not frequently), we can add/change enum as well. A example where the reasons are pre-defined.

**Comment by marcjudge** [comment]
> 

I might revisit this in a patch release when I'm more familiar with ref data. For now I just want to make sure I can interact with it and be able write tests that don't rely on local version of et-data-model

**Pull request merged**
